// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"net/http"

	"example.com/classic/internal/config"
	"example.com/classic/internal/data/ent"
	"example.com/classic/internal/data/redis"
	"example.com/classic/internal/data/store/entstore"
	"example.com/classic/internal/handler"
	"example.com/classic/internal/job/asynq"
	"example.com/classic/internal/repository"
	httpserver "example.com/classic/internal/server/http"
	"example.com/classic/internal/service"
	"example.com/classic/pkg/logger"
)

// InitHTTPServer 返回完整的 HTTP Server 和配置
func InitHTTPServer(ctx context.Context) (*http.Server, *config.Config, logger.Logger, error) {
	// 加载配置
	cfg, err := config.Load()
	if err != nil {
		return nil, nil, nil, err
	}

	// 创建日志实例
	log := provideLogger(cfg)

	// 创建数据存储
	store, err := entstore.New(ctx, cfg, log)
	if err != nil {
		return nil, nil, nil, err
	}

	// 提供 Ent 客户端
	entClient := provideEntClient(store)

	// 创建 Redis 客户端
	redisClient, err := redis.New(cfg, log)
	if err != nil {
		return nil, nil, nil, err
	}
	_ = redisClient // 暂未使用

	// 创建任务队列
	taskQueue, err := asynq.New(cfg, log)
	if err != nil {
		return nil, nil, nil, err
	}

	// 创建用户仓储
	userRepo := repository.NewUserRepository(entClient, log)

	// 创建用户服务（传入任务队列）
	userService := service.NewUserService(userRepo, taskQueue, log)

	// 创建用户处理器
	userHandler := handler.NewUserHandler(userService, log)

	// 创建 HTTP 服务器
	server := httpserver.NewServer(cfg, log, userHandler)

	// 获取 HTTP 服务器实例
	httpServer := provideHTTPServer(server)

	return httpServer, cfg, log, nil
}

// provideLogger 提供日志实例
func provideLogger(cfg *config.Config) logger.Logger {
	log := logger.New(cfg.Service, cfg.Log.Level, cfg.IsDevelopment())
	logger.SetGlobalLogger(log)
	return log
}

// provideEntClient 提供 Ent 客户端
func provideEntClient(store *entstore.Store) *ent.Client {
	return store.Client
}

// provideHTTPServer 提供 HTTP 服务器
func provideHTTPServer(server *httpserver.Server) *http.Server {
	return server.GetHTTPServer()
}
