// Code generated by Wire. DO NOT EDIT.

package wire

import (
	"context"
	"net/http"
	"time"

	appuser "example.com/classic/internal/app/user"
	"example.com/classic/internal/config"
	"example.com/classic/internal/data/ent"
	"example.com/classic/internal/data/store/entstore"
	"example.com/classic/internal/logger"
	httpserver "example.com/classic/internal/server/http"
	"example.com/classic/internal/server/http/router"
	"github.com/gin-gonic/gin"
)

// InitHTTPServer 返回完整的 HTTP Server 和配置
func InitHTTPServer(ctx context.Context) (*http.Server, *config.Config, *logger.Logger, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, nil, nil, err
	}
	log := logger.New(cfg)
	store, err := entstore.New(ctx, cfg, log)
	if err != nil {
		return nil, nil, nil, err
	}
	var client *ent.Client = provideEntClient(store)
	repo := appuser.NewRepository(client)
	service := appuser.NewService(repo)
	userHandler := router.NewUserHandler(service)
	engine := httpserver.BuildEngine(cfg, log, userHandler)
	server := provideHTTPServer(cfg, engine)
	return server, cfg, log, nil
}

func provideEntClient(store *entstore.Store) *ent.Client { return store.Client }

func provideHTTPServer(cfg *config.Config, engine *gin.Engine) *http.Server {
	return &http.Server{
		Addr:              cfg.HTTP.Address,
		Handler:           engine,
		ReadTimeout:       10 * time.Second,
		ReadHeaderTimeout: 10 * time.Second,
		WriteTimeout:      20 * time.Second,
		IdleTimeout:       60 * time.Second,
		MaxHeaderBytes:    1 << 20,
	}
}
