// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Status string

const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
)

func (s Status) IsValid() bool {
	switch s {
	case StatusActive, StatusInactive:
		return true
	default:
		return false
	}
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	Status    Status
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Null* types for nullable fields
type NullStatus struct {
	Status Status
	Valid  bool
}

type NullInt32 struct {
	Int32 int32
	Valid bool
}

type NullString struct {
	String string
	Valid  bool
}

type NullTime struct {
	Time  time.Time
	Valid bool
}

// ToNullInt32 converts *int to NullInt32
func ToNullInt32(i *int) NullInt32 {
	if i == nil {
		return NullInt32{Valid: false}
	}
	return NullInt32{Int32: int32(*i), Valid: true}
}

// ToNullString converts *string to NullString
func ToNullString(s *string) NullString {
	if s == nil {
		return NullString{Valid: false}
	}
	return NullString{String: *s, Valid: true}
}

// ToNullStatus converts *Status to NullStatus
func ToNullStatus(s *Status) NullStatus {
	if s == nil {
		return NullStatus{Valid: false}
	}
	return NullStatus{Status: *s, Valid: true}
}

// UserDTO represents user data for transfer
type UserDTO struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Status    Status    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ToDTO converts User to UserDTO (excludes password)
func (u *User) ToDTO() UserDTO {
	return UserDTO{
		ID:        u.ID,
		Name:      u.Name,
		Email:     u.Email,
		Status:    u.Status,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}
}
