// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

type Queries struct {
	db DBTX
}

type DBTX interface {
	ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
	PrepareContext(ctx context.Context, query string) (*sql.Stmt, error)
	QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}

// CreateUserParams represents parameters for CreateUser
type CreateUserParams struct {
	Name      string
	Email     string
	Password  string
	Status    Status
	CreatedAt time.Time
	UpdatedAt time.Time
}

// CreateUser inserts a new user and returns the created record
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	const query = `
		INSERT INTO users (name, email, password, status, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?)
	`
	result, err := q.db.ExecContext(ctx, query,
		arg.Name,
		arg.Email,
		arg.Password,
		string(arg.Status),
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return User{}, fmt.Errorf("create user: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return User{}, fmt.Errorf("get last insert id: %w", err)
	}

	return q.GetUserByID(ctx, int32(id))
}

// GetUserByID retrieves a user by ID
func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	const query = `SELECT id, name, email, password, status, created_at, updated_at FROM users WHERE id = ? LIMIT 1`

	var user User
	var statusStr string
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&user.ID,
		&user.Name,
		&user.Email,
		&user.Password,
		&statusStr,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		return User{}, fmt.Errorf("get user by id: %w", err)
	}
	user.Status = Status(statusStr)
	return user, nil
}

// GetUserByEmail retrieves a user by email
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	const query = `SELECT id, name, email, password, status, created_at, updated_at FROM users WHERE email = ? LIMIT 1`

	var user User
	var statusStr string
	err := q.db.QueryRowContext(ctx, query, email).Scan(
		&user.ID,
		&user.Name,
		&user.Email,
		&user.Password,
		&statusStr,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		return User{}, fmt.Errorf("get user by email: %w", err)
	}
	user.Status = Status(statusStr)
	return user, nil
}

// UpdateUserParams represents parameters for UpdateUser
type UpdateUserParams struct {
	Name      string
	Email     string
	Status    Status
	UpdatedAt time.Time
	ID        int32
}

// UpdateUser updates a user and returns the updated record
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	const query = `
		UPDATE users
		SET name = ?, email = ?, status = ?, updated_at = ?
		WHERE id = ?
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.Name,
		arg.Email,
		string(arg.Status),
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return User{}, fmt.Errorf("update user: %w", err)
	}

	return q.GetUserByID(ctx, arg.ID)
}

// DeleteUser deletes a user by ID
func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	const query = `DELETE FROM users WHERE id = ?`
	_, err := q.db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("delete user: %w", err)
	}
	return nil
}

// ListUsersParams represents parameters for ListUsers
type ListUsersParams struct {
	ID       NullInt32
	Name     NullString
	Email    NullString
	Status   NullStatus
	Limit    int32
	Offset   int32
}

// ListUsers retrieves a paginated list of users
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	const query = `
		SELECT id, name, email, password, status, created_at, updated_at FROM users
		WHERE (? IS NULL OR id = ?)
		  AND (? IS NULL OR name LIKE CONCAT('%', ?, '%'))
		  AND (? IS NULL OR email LIKE CONCAT('%', ?, '%'))
		  AND (? IS NULL OR status = ?)
		ORDER BY id DESC
		LIMIT ? OFFSET ?
	`

	var statusVal interface{}
	if arg.Status.Valid {
		statusVal = string(arg.Status.Status)
	} else {
		statusVal = nil
	}

	var idVal, idCond interface{}
	if arg.ID.Valid {
		idVal = arg.ID.Int32
		idCond = arg.ID.Int32
	} else {
		idVal = nil
		idCond = nil
	}

	var nameVal, nameCond interface{}
	if arg.Name.Valid {
		nameVal = arg.Name.String
		nameCond = arg.Name.String
	} else {
		nameVal = nil
		nameCond = nil
	}

	var emailVal, emailCond interface{}
	if arg.Email.Valid {
		emailVal = arg.Email.String
		emailCond = arg.Email.String
	} else {
		emailVal = nil
		emailCond = nil
	}

	rows, err := q.db.QueryContext(ctx, query,
		idVal, idCond,
		nameVal, nameCond,
		emailVal, emailCond,
		statusVal, statusVal,
		arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, fmt.Errorf("list users: %w", err)
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var user User
		var statusStr string
		if err := rows.Scan(
			&user.ID,
			&user.Name,
			&user.Email,
			&user.Password,
			&statusStr,
			&user.CreatedAt,
			&user.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan user: %w", err)
		}
		user.Status = Status(statusStr)
		users = append(users, user)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}

	return users, nil
}

// CountUsersParams represents parameters for CountUsers
type CountUsersParams struct {
	ID     NullInt32
	Name   NullString
	Email  NullString
	Status NullStatus
}

// CountUsers counts users matching the criteria
func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	const query = `
		SELECT COUNT(*) as count FROM users
		WHERE (? IS NULL OR id = ?)
		  AND (? IS NULL OR name LIKE CONCAT('%', ?, '%'))
		  AND (? IS NULL OR email LIKE CONCAT('%', ?, '%'))
		  AND (? IS NULL OR status = ?)
	`

	var statusVal interface{}
	if arg.Status.Valid {
		statusVal = string(arg.Status.Status)
	} else {
		statusVal = nil
	}

	var idVal, idCond interface{}
	if arg.ID.Valid {
		idVal = arg.ID.Int32
		idCond = arg.ID.Int32
	} else {
		idVal = nil
		idCond = nil
	}

	var nameVal, nameCond interface{}
	if arg.Name.Valid {
		nameVal = arg.Name.String
		nameCond = arg.Name.String
	} else {
		nameVal = nil
		nameCond = nil
	}

	var emailVal, emailCond interface{}
	if arg.Email.Valid {
		emailVal = arg.Email.String
		emailCond = arg.Email.String
	} else {
		emailVal = nil
		emailCond = nil
	}

	var count int64
	err := q.db.QueryRowContext(ctx, query,
		idVal, idCond,
		nameVal, nameCond,
		emailVal, emailCond,
		statusVal, statusVal,
	).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("count users: %w", err)
	}

	return count, nil
}

// ExistsByEmail checks if a user with the given email exists
func (q *Queries) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	const query = `SELECT EXISTS(SELECT 1 FROM users WHERE email = ?)`

	var exists bool
	err := q.db.QueryRowContext(ctx, query, email).Scan(&exists)
	if err != nil {
		return false, fmt.Errorf("exists by email: %w", err)
	}
	return exists, nil
}
